version: '2.1'
services:
  node1:
    image: kv:${TAG}
    container_name: kv-1
    ports:
      - "8081:8080"
    volumes:
      - ./cfg/node1.toml:/etc/cfg.toml
      - ./logs:/apps/matrixbase/distributed/logs
    networks:
      mynet1:
        ipv4_address: 172.19.1.1

  node2:
    image: kv:${TAG}
    container_name: kv-2
    ports:
      - "8082:8080"
    volumes:
      - ./cfg/node2.toml:/etc/cfg.toml
      - ./logs:/apps/matrixbase/distributed/logs
    networks:
      mynet1:
        ipv4_address: 172.19.1.2

#  node3:
#    image: kv:${TAG}
#    container_name: kv-3
#    ports:
#      - "8083:8080"
#    volumes:
#      - ./cfg/node3.toml:/etc/cfg.toml
#      - ./logs:/apps/matrixbase/distributed/logs
#    networks:
#      mynet1:
#        ipv4_address: 172.19.1.3



networks:
  mynet1:
    ipam:
      config:
        - subnet: 172.19.0.0/16