version: '2.1'
services:
  node1:
    dns:
      - 8.8.8.8
    network_mode: "host"
    image: kv:${TAG}
    container_name: kv-1
    ports:
      - "8081:8080"
    volumes:
      - ./cfg/node1.toml:/etc/cfg.toml
      - ./logs:/apps/matrixbase/distributed/logs

#  node2:
#    network_mode: "host"
#    image: kv:${TAG}
#    container_name: kv-2
#    ports:
#      - "8082:8080"
#    volumes:
#      - ./cfg/node2.toml:/etc/cfg.toml
#      - ./logs:/apps/matrixbase/distributed/logs
#
#  node3:
#    network_mode: "host"
#    image: kv:${TAG}
#    container_name: kv-3
#    ports:
#      - "8083:8080"
#    volumes:
#      - ./cfg/node3.toml:/etc/cfg.toml
#      - ./logs:/apps/matrixbase/distributed/logs